"""add dptment

Revision ID: ca748909d709
Revises: 0cc1854ff2a8
Create Date: 2019-09-26 00:42:56.798863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca748909d709'
down_revision = '0cc1854ff2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('department', sa.String(length=64), nullable=False))
    op.alter_column('components', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('components', 'quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('components', 'totalPrice',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('components', 'type',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('components', 'unitPrice',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('components', 'unitPrice',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('components', 'type',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('components', 'totalPrice',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('components', 'quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('components', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_column('components', 'department')
    # ### end Alembic commands ###
